### ISSUE TITLE
When running a 'scan all' complains of hitting break point

### ISSUE THREAD

**Issue by ctolkien** [leetreveil/Zune-Social-Tagger#9] opened 2011-08-29 14:24 UTC
<img src="http://i.imgur.com/zk45R.png" />

**Comment by leetreveil** [comment] 2011-09-01 14:27
Once I release the next version of ZST can you let me know if this error still exists?

**Comment by ctolkien** [comment] 2011-09-08 04:30
Problem persists with 2.4.1

**Comment by leetreveil** [comment] 2011-09-09 10:12
I can't reproduce this error. Googling isn't helping either. Is there any more information you can give me?

**Comment by leetreveil** [comment] 2011-09-10 15:02
Fixed in commit 4d2d9b6

**Closed as completed by leetreveil** 2011-09-10 15:02 UTC
