### ISSUE TITLE
Major UI Bug

### ISSUE THREAD

**Issue by Seketh** [leetreveil/Zune-Social-Tagger#12] opened 2011-09-22 09:22 UTC
Major UI Bug, screenshot:

http://img15.imageshack.us/img15/4981/issuea.jpg

As you can see, the application accumulates previous searches and links. I have a large collection of singles, and this issue makes the UI confusing and unusable.

All my files are in .m4a, so that might be related. 

On a sidenote, it would be awesome if you could give us the option of what metadata to update, since some of the Zune Marketplace metadata is incorrect.

Oh, and by the way, with the Mango release of WP7, lots of countries which don't have acess to the music marketplace and Zune Pass will have to use your app to get cover flow, so now might be the right time to promote your app in all major WP7 blogs and forums, I'm sure your downloads will grow immensely.

Thank you for the app!

**Comment by leetreveil** [comment] 2011-09-27 12:20
I am unable to reproduce this bug, can you lead me through the steps so I can test this? Thanks.

**Comment by Seketh** [comment] 2011-10-06 22:54
I don't do anything special. 

I just start the application - search one song - link it or not - search another, but the previous search still shows like in the screenshot I provided.)

**Comment by leetreveil** [comment] 2011-10-07 17:22
Ok, I think i've identified the issue. See if it's fixed in the next update.

**Closed as completed** 2011-10-07 17:23 UTC
